### ISSUE TITLE
Need help creating a better README.md for this repo !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/amongus-moderator#1]
Hey ! So the project is pretty much done. I need help with creating a better README for this repo. Suggest some good edits please. Happy Hacktoberfest !

**Comment by InternetRamen** [comment]
I will try doing this.

**Comment by InternetRamen** [comment]
Could you please add the topic hacktoberfest to the repo so I could get credit in hacktoberfest?

Also #2

**Comment by Nikzy7** [comment]
@InternetRamen sure... I'm looking into it !

**Comment by gargmanvi** [comment]
I also want to work on this. Please assign this to me!

**Comment by Nikzy7** [comment]
@gargmanvi done !

**Comment by Nikzy7** [comment]
Thank You everyone for your PRs.
